-- Citrinia schema.
-- Reconstructed from the original Supabase project's backup (paused 2024-07-31),
-- with three fixes marked "fix:" inline. Apply once to a fresh project via the
-- dashboard SQL editor (or `supabase db push` if you use the CLI).

create table public.profiles (
  id uuid primary key references auth.users (id) on update cascade on delete cascade,
  name text not null,
  username text not null,
  avatar_url text not null
);

create table public.peels (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  title text not null,
  user_id uuid not null references public.profiles (id) on update cascade on delete cascade,
  -- fix: original accepted empty and unbounded titles
  constraint peels_title_length check (char_length(title) between 1 and 280)
);

create table public.likes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references public.profiles (id) on update cascade on delete cascade,
  peel_id uuid not null references public.peels (id) on update cascade on delete cascade,
  -- fix: original let one user like the same peel more than once
  constraint likes_user_peel_unique unique (user_id, peel_id)
);

-- Create a profile row from GitHub OAuth metadata when a user signs up.
create or replace function public.insert_profile_for_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, name, username, avatar_url)
  values (
    new.id,
    -- fix: GitHub users with no display name have a null "name", which aborted signup
    coalesce(new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'user_name'),
    new.raw_user_meta_data->>'user_name',
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
$$;

create trigger add_profile_after_login
  after insert on auth.users
  for each row execute function public.insert_profile_for_new_user();

-- Row-level security (same policies as the original project).
alter table public.profiles enable row level security;
alter table public.peels enable row level security;
alter table public.likes enable row level security;

create policy "enable read access for profiles"
  on public.profiles for select using (true);

create policy "authenticated users can select peels"
  on public.peels for select to authenticated using (true);
create policy "authenticated users can insert their own peels"
  on public.peels for insert to authenticated with check (user_id = auth.uid());

create policy "anyone can select likes"
  on public.likes for select using (true);
create policy "authenticated user can like peels"
  on public.likes for insert to authenticated with check (user_id = auth.uid());
create policy "authenticated users can unlike peels"
  on public.likes for delete to authenticated using (user_id = auth.uid());

-- Data API grants, scoped to what the policies above allow. Explicit so the app
-- works whether or not the project has "automatically expose new tables" on.
grant select on public.profiles to anon, authenticated;
grant select, insert on public.peels to authenticated;
grant select on public.likes to anon, authenticated;
grant insert, delete on public.likes to authenticated;
grant usage on sequence public.likes_id_seq to authenticated;

-- Realtime: the feed subscribes to changes on peels.
alter publication supabase_realtime add table public.peels;
