-- Citrinia social layer: reposts ("repeel"), quote peels, private bookmarks,
-- media attachments, notifications (with @mention detection in the database),
-- and the merged home timeline. Apply after 20260906000000_core.sql via the
-- dashboard SQL editor (or `supabase db push`).

--------------------------------------------------------------------------------
-- Quote peels
--------------------------------------------------------------------------------

-- A quote is an ordinary top-level peel that embeds another one. Composting the
-- quoted peel leaves the quote standing as a plain peel, which is why this is
-- "set null" rather than the cascade parent_id uses.
alter table public.peels
  add column quote_id uuid references public.peels (id) on update cascade on delete set null;

create index peels_quote_id_idx on public.peels (quote_id);

--------------------------------------------------------------------------------
-- Reposts
--------------------------------------------------------------------------------

-- One repost per user per peel. Reposting your own peel is allowed (it is how a
-- peel gets a second run at the timeline); the notification trigger just never
-- tells you about yourself.
create table public.reposts (
  user_id uuid not null references public.profiles (id) on update cascade on delete cascade,
  peel_id uuid not null references public.peels (id) on update cascade on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, peel_id)
);

-- "what did ada repost, newest first" for the timeline; the second one is
-- "who reposted this peel" for the card's count.
create index reposts_user_created_idx on public.reposts (user_id, created_at desc);
create index reposts_peel_id_idx on public.reposts (peel_id);

alter table public.reposts enable row level security;

create policy "authenticated users can select reposts"
  on public.reposts for select to authenticated using (true);
create policy "authenticated users can repost"
  on public.reposts for insert to authenticated with check (user_id = auth.uid());
create policy "authenticated users can unrepost"
  on public.reposts for delete to authenticated using (user_id = auth.uid());

grant select, insert, delete on public.reposts to authenticated;

--------------------------------------------------------------------------------
-- Bookmarks (private: only the owner may read them)
--------------------------------------------------------------------------------

create table public.bookmarks (
  user_id uuid not null references public.profiles (id) on update cascade on delete cascade,
  peel_id uuid not null references public.peels (id) on update cascade on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, peel_id)
);

create index bookmarks_user_created_idx on public.bookmarks (user_id, created_at desc);
create index bookmarks_peel_id_idx on public.bookmarks (peel_id);

alter table public.bookmarks enable row level security;

-- Unlike likes and reposts, a bookmark is nobody else's business. The select
-- policy is what makes `bookmarks(user_id)` embedded on a peel read as "did I
-- bookmark this" instead of "who bookmarked this".
create policy "users can select their own bookmarks"
  on public.bookmarks for select to authenticated using (user_id = auth.uid());
create policy "users can bookmark peels"
  on public.bookmarks for insert to authenticated with check (user_id = auth.uid());
create policy "users can unbookmark peels"
  on public.bookmarks for delete to authenticated using (user_id = auth.uid());

grant select, insert, delete on public.bookmarks to authenticated;

--------------------------------------------------------------------------------
-- Media attachments
--------------------------------------------------------------------------------

-- Up to four per peel in the app; the database only enforces one row per
-- (peel, position). `url` is an external https link -- either somebody else's
-- CDN or a public object in the `media` Storage bucket created at the bottom of
-- this file.
create table public.peel_media (
  id bigint generated by default as identity primary key,
  peel_id uuid not null references public.peels (id) on update cascade on delete cascade,
  position smallint not null default 0,
  kind text not null
    constraint peel_media_kind check (kind in ('image', 'gif', 'video', 'youtube')),
  url text not null
    -- https, or a loopback URL from a local Supabase stack (local Storage serves http://127.0.0.1).
    constraint peel_media_url_https check (url ~ '^https://' or url ~ '^http://(127\.0\.0\.1|localhost)(:[0-9]+)?/'),
  alt text not null default ''
    constraint peel_media_alt_length check (char_length(alt) <= 200),
  width int,
  height int,
  constraint peel_media_peel_position_unique unique (peel_id, position)
);

alter table public.peel_media enable row level security;

create policy "authenticated users can select peel media"
  on public.peel_media for select to authenticated using (true);
-- Media hangs off a peel, so the peel's author is the only one who may attach or
-- detach it. Without this a signed-in user could staple anything to your peel.
create policy "authors can attach media to their own peels"
  on public.peel_media for insert to authenticated
  with check (exists (select 1 from public.peels p where p.id = peel_id and p.user_id = auth.uid()));
create policy "authors can detach media from their own peels"
  on public.peel_media for delete to authenticated
  using (exists (select 1 from public.peels p where p.id = peel_id and p.user_id = auth.uid()));

grant select, insert, delete on public.peel_media to authenticated;
grant usage on sequence public.peel_media_id_seq to authenticated;

--------------------------------------------------------------------------------
-- Notifications
--------------------------------------------------------------------------------

-- Written only by the triggers below (which are security definer, so they write
-- past RLS). Users can read their own and mark them read; they cannot insert,
-- delete, or forge one, because there is no policy and no grant for either.
create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null
    constraint notifications_user_id_fkey references public.profiles (id) on update cascade on delete cascade,
  actor_id uuid not null
    constraint notifications_actor_id_fkey references public.profiles (id) on update cascade on delete cascade,
  type text not null
    constraint notifications_type check (type in ('like', 'reply', 'quote', 'mention', 'follow', 'repost')),
  peel_id uuid
    constraint notifications_peel_id_fkey references public.peels (id) on update cascade on delete cascade,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  -- Belt and braces: every trigger already skips the actor, so a row that says
  -- "you liked your own peel" would be a bug, not data.
  constraint notifications_not_self check (user_id <> actor_id),
  -- "nulls not distinct" is what makes a second follow notification collide:
  -- follow rows carry a null peel_id, and the default null semantics would let
  -- them stack up forever.
  constraint notifications_unique unique nulls not distinct (user_id, actor_id, type, peel_id)
);

create index notifications_user_created_idx on public.notifications (user_id, created_at desc);
-- The bell only ever asks for the unread count, so it gets its own partial index.
create index notifications_unread_idx on public.notifications (user_id) where read_at is null;

alter table public.notifications enable row level security;

create policy "users can select their own notifications"
  on public.notifications for select to authenticated using (user_id = auth.uid());
create policy "users can mark their own notifications read"
  on public.notifications for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- read_at is the only column a user may write: a column grant, because a policy
-- cannot restrict columns.
grant select on public.notifications to authenticated;
grant update (read_at) on public.notifications to authenticated;

--------------------------------------------------------------------------------
-- Notification triggers
--------------------------------------------------------------------------------
-- All security definer with an empty search_path, so they write past RLS but can
-- only see fully-qualified objects. Every insert is "on conflict do nothing":
-- the unique constraint is what stops a like/unlike/like from stacking up rows.

create or replace function public.notify_on_like()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare author uuid;
begin
  select p.user_id into author from public.peels p where p.id = new.peel_id;
  -- Liking your own peel notifies nobody.
  if author is null or author = new.user_id then return new; end if;
  insert into public.notifications (user_id, actor_id, type, peel_id)
  values (author, new.user_id, 'like', new.peel_id)
  on conflict do nothing;
  return new;
end;
$$;

create or replace function public.unnotify_on_like()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.notifications n
  where n.actor_id = old.user_id and n.type = 'like' and n.peel_id = old.peel_id;
  return old;
end;
$$;

create trigger notify_like after insert on public.likes
  for each row execute function public.notify_on_like();
create trigger unnotify_like after delete on public.likes
  for each row execute function public.unnotify_on_like();

create or replace function public.notify_on_repost()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare author uuid;
begin
  select p.user_id into author from public.peels p where p.id = new.peel_id;
  -- Reposting your own peel is allowed, it just does not notify you.
  if author is null or author = new.user_id then return new; end if;
  insert into public.notifications (user_id, actor_id, type, peel_id)
  values (author, new.user_id, 'repost', new.peel_id)
  on conflict do nothing;
  return new;
end;
$$;

create or replace function public.unnotify_on_repost()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.notifications n
  where n.actor_id = old.user_id and n.type = 'repost' and n.peel_id = old.peel_id;
  return old;
end;
$$;

create trigger notify_repost after insert on public.reposts
  for each row execute function public.notify_on_repost();
create trigger unnotify_repost after delete on public.reposts
  for each row execute function public.unnotify_on_repost();

create or replace function public.notify_on_follow()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  -- follows_not_self already rejects following yourself.
  insert into public.notifications (user_id, actor_id, type, peel_id)
  values (new.followee_id, new.follower_id, 'follow', null)
  on conflict do nothing;
  return new;
end;
$$;

create or replace function public.unnotify_on_follow()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.notifications n
  where n.user_id = old.followee_id and n.actor_id = old.follower_id
    and n.type = 'follow' and n.peel_id is null;
  return old;
end;
$$;

create trigger notify_follow after insert on public.follows
  for each row execute function public.notify_on_follow();
create trigger unnotify_follow after delete on public.follows
  for each row execute function public.unnotify_on_follow();

-- One trigger for the three things a new peel can announce: it replies to
-- someone, it quotes someone, and it mentions people by handle. The author never
-- gets notified, and nobody gets two notifications for the same peel -- being
-- the parent's author already told you about it, so a "@them" in the same peel
-- is not a second event.
create or replace function public.notify_on_peel()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  other uuid;
  handle text;
  notified uuid[] := array[]::uuid[];
begin
  if new.parent_id is not null then
    select p.user_id into other from public.peels p where p.id = new.parent_id;
    if other is not null and other <> new.user_id then
      insert into public.notifications (user_id, actor_id, type, peel_id)
      values (other, new.user_id, 'reply', new.id) on conflict do nothing;
      notified := notified || other;
    end if;
  end if;

  if new.quote_id is not null then
    select p.user_id into other from public.peels p where p.id = new.quote_id;
    if other is not null and other <> new.user_id and not (other = any (notified)) then
      insert into public.notifications (user_id, actor_id, type, peel_id)
      values (other, new.user_id, 'quote', new.id) on conflict do nothing;
      notified := notified || other;
    end if;
  end if;

  -- Handles are matched lower-case because GitHub logins are case-insensitive
  -- while raw_user_meta_data keeps whatever case the user typed.
  for handle in
    -- Same boundary rule as lib/text.ts: an @ glued to a preceding word character
    -- (an email address, say) is not a mention. Lower-cased so @Bob finds bob.
    select distinct m[1] from regexp_matches(lower(new.title), '(?:^|[^a-z0-9_])@([a-z0-9_]{3,20})', 'g') as m
  loop
    select pr.id into other from public.profiles pr where lower(pr.username) = handle limit 1;
    if other is not null and other <> new.user_id and not (other = any (notified)) then
      insert into public.notifications (user_id, actor_id, type, peel_id)
      values (other, new.user_id, 'mention', new.id) on conflict do nothing;
      notified := notified || other;
    end if;
  end loop;

  return new;
end;
$$;

create trigger notify_peel after insert on public.peels
  for each row execute function public.notify_on_peel();

--------------------------------------------------------------------------------
-- Home timeline
--------------------------------------------------------------------------------

-- Peels and reposts merged into one cursor-paginated stream. Returns ids only:
-- the app hydrates them through lib/peels.ts so every screen shapes a peel the
-- same way. A peel can come back twice (once itself, once as somebody's repost),
-- which is deliberate -- they are different events at different times.
--
--   following_only  restrict to who the viewer follows, plus the viewer
--   before          keyset cursor: return rows strictly older than this
--   page_size       clamped to 1..100
--
-- Security invoker on purpose: RLS on peels/reposts/follows is what scopes it,
-- and auth.uid() is the caller's.
create or replace function public.home_timeline(
  following_only boolean default false,
  before timestamptz default null,
  page_size int default 20
)
returns table (peel_id uuid, repost_by uuid, sort_at timestamptz)
language sql
stable
security invoker
set search_path = ''
as $$
  with allowed as (
    select f.followee_id as id from public.follows f where f.follower_id = auth.uid()
    union
    select auth.uid() as id
  )
  select p.id, null::uuid, p.created_at
  from public.peels p
  where p.parent_id is null
    and (not coalesce(following_only, false) or p.user_id in (select a.id from allowed a))
    and p.created_at < coalesce(before, now() + interval '1 day')
  union all
  select r.peel_id, r.user_id, r.created_at
  from public.reposts r
  join public.peels p on p.id = r.peel_id and p.parent_id is null
  where (not coalesce(following_only, false) or r.user_id in (select a.id from allowed a))
    and r.created_at < coalesce(before, now() + interval '1 day')
  order by 3 desc
  -- A null page_size would make greatest() return 1, i.e. a one-row page; a
  -- caller who leaves it out means the default.
  limit least(greatest(coalesce(page_size, 20), 1), 100);
$$;

-- Supabase's default privileges hand EXECUTE on new functions to anon and
-- authenticated, so revoking from PUBLIC alone would not be enough.
revoke execute on function public.home_timeline(boolean, timestamptz, int) from public, anon, authenticated;
grant execute on function public.home_timeline(boolean, timestamptz, int) to authenticated;

--------------------------------------------------------------------------------
-- Bulk-seed switch
--------------------------------------------------------------------------------

-- Seeding a few thousand peels/likes/follows with the notification triggers on
-- writes a notification per row and takes minutes. This turns them off for the
-- duration. Service role only, twice over: EXECUTE is granted to service_role
-- alone, and the body re-checks the request's JWT claim so a leaked grant is not
-- enough. From the SQL editor (which runs as postgres) set the claim first:
--   select set_config('request.jwt.claim.role', 'service_role', true);
--   select public.seed_triggers(false);
create or replace function public.seed_triggers(enabled boolean)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  -- PostgREST < 10 set request.jwt.claim.role; later versions set the whole
  -- claims object. session_user covers a direct psql connection as service_role.
  if coalesce(
       nullif(current_setting('request.jwt.claim.role', true), ''),
       nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'role',
       session_user::text
     ) is distinct from 'service_role' then
    raise exception 'seed_triggers() is for the service role only'
      using errcode = 'insufficient_privilege';
  end if;

  if enabled then
    alter table public.likes enable trigger notify_like;
    alter table public.likes enable trigger unnotify_like;
    alter table public.reposts enable trigger notify_repost;
    alter table public.reposts enable trigger unnotify_repost;
    alter table public.follows enable trigger notify_follow;
    alter table public.follows enable trigger unnotify_follow;
    alter table public.peels enable trigger notify_peel;
  else
    alter table public.likes disable trigger notify_like;
    alter table public.likes disable trigger unnotify_like;
    alter table public.reposts disable trigger notify_repost;
    alter table public.reposts disable trigger unnotify_repost;
    alter table public.follows disable trigger notify_follow;
    alter table public.follows disable trigger unnotify_follow;
    alter table public.peels disable trigger notify_peel;
  end if;
end;
$$;

revoke execute on function public.seed_triggers(boolean) from public, anon, authenticated;
grant execute on function public.seed_triggers(boolean) to service_role;


--------------------------------------------------------------------------------
-- Storage: the `media` bucket
--------------------------------------------------------------------------------

-- Uploads go straight from the browser to Storage, into a folder named after the
-- uploader's uid, and the resulting public URL lands in peel_media.url.
--
-- Everything here looks before it writes. The `storage` schema is owned by the
-- platform, not by us: the throwaway postgres container in supabase/verify.sh
-- ships it empty (the tables belong to storage-api's own migrations), older
-- projects lack the newer buckets columns, and on some projects the `postgres`
-- role cannot create policies on storage.objects at all. None of those should
-- abort a migration whose real subject is the public schema, so this returns a
-- status line instead of raising. Idempotent: safe to run again.
--
-- If it reports that it could not do the storage half, create the bucket in
-- Dashboard -> Storage (public, 25 MB, image/jpeg image/png image/gif image/webp
-- video/mp4 video/webm) and add the three policies from Storage -> Policies.
create or replace function public.ensure_media_bucket()
returns text
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  mimes constant text :=
    $v$array['image/jpeg','image/png','image/gif','image/webp','video/mp4','video/webm']::text[]$v$;
  cols text[];
  col_list text := 'id, name, public';
  val_list text := $v$'media', 'media', true$v$;
  made int := 0;
begin
  if to_regclass('storage.buckets') is null then
    return 'skipped: no storage.buckets in this database';
  end if;

  select array_agg(c.column_name::text) into cols
  from information_schema.columns c
  where c.table_schema = 'storage' and c.table_name = 'buckets';

  -- 25 MB, and only the types the composer can render. Both columns arrived
  -- after the original storage schema, so neither is assumed.
  if 'file_size_limit' = any (cols) then
    col_list := col_list || ', file_size_limit';
    val_list := val_list || ', 26214400';
  end if;
  if 'allowed_mime_types' = any (cols) then
    col_list := col_list || ', allowed_mime_types';
    val_list := val_list || ', ' || mimes;
  end if;

  begin
    execute format('insert into storage.buckets (%s) values (%s) on conflict (id) do nothing',
                   col_list, val_list);
    -- A bucket that already exists (a re-run, or one made in the dashboard) is
    -- brought in line with this migration.
    execute 'update storage.buckets set public = true where id = ''media''';
    if 'file_size_limit' = any (cols) then
      execute 'update storage.buckets set file_size_limit = 26214400 where id = ''media''';
    end if;
    if 'allowed_mime_types' = any (cols) then
      execute 'update storage.buckets set allowed_mime_types = ' || mimes || ' where id = ''media''';
    end if;
  exception when insufficient_privilege then
    return 'skipped: no rights on storage.buckets; create the media bucket in the dashboard';
  end;

  if to_regclass('storage.objects') is null then
    return 'bucket ready; no storage.objects, so no policies';
  end if;

  -- Public read, because peel_media.url is handed to <img>. Writes are confined
  -- to a folder named after the uploader's uid, so nobody can overwrite anybody
  -- else's file, and delete is limited to your own folder too.
  begin
    if not exists (select 1 from pg_policies
                   where schemaname = 'storage' and tablename = 'objects'
                     and policyname = 'media is publicly readable') then
      execute $v$create policy "media is publicly readable" on storage.objects
                for select using (bucket_id = 'media')$v$;
      made := made + 1;
    end if;
    if not exists (select 1 from pg_policies
                   where schemaname = 'storage' and tablename = 'objects'
                     and policyname = 'users upload media to their own folder') then
      execute $v$create policy "users upload media to their own folder" on storage.objects
                for insert to authenticated
                with check (bucket_id = 'media'
                            and (storage.foldername(name))[1] = auth.uid()::text)$v$;
      made := made + 1;
    end if;
    if not exists (select 1 from pg_policies
                   where schemaname = 'storage' and tablename = 'objects'
                     and policyname = 'users delete their own media') then
      execute $v$create policy "users delete their own media" on storage.objects
                for delete to authenticated
                using (bucket_id = 'media'
                       and (storage.foldername(name))[1] = auth.uid()::text)$v$;
      made := made + 1;
    end if;
  exception when insufficient_privilege then
    return 'bucket ready; no rights on storage.objects, add its 3 policies in the dashboard';
  end;

  return format('bucket ready; %s storage policies added, 3 in place', made);
end;
$fn$;

revoke execute on function public.ensure_media_bucket() from public, anon, authenticated;

do $$ begin raise notice 'media bucket: %', public.ensure_media_bucket(); end $$;
